<?php
$confconfig = 
  array(
   array('answers' =>
    array('e' => array("Excellent", "Good", "Acceptable", "Poor", 
                       "Not Applicable"),
     'e1' => array("Excellent", "Good", "Acceptable", "Poor"),
     'cost' => array("\$200", "\$225", "\$250", "\$275", "\$300", "\$325"),
     'paidby' => array("Self", "Reimb. by employer", 
                       "Paid directly by employer"),
     'handouts' => array("Paper Copies", "CD", "Website", 
                         "Paper Copies & CD"))),

   array('q' => "1a", 
         'text' => "Have you previously attended an OCEAN conference?", 
         'reporton' => 'mc', 'qtype' => 'yn'),
   array('q' => "1b", 'text' => "If Yes, how many have you attended?", 
         'reporton' => 'avg', 'qtype' => 'number'),
   array('q' => "2", 'text' => "Number of Sessions Attended", 
         'reporton' => 'pct',
         'qtype' => 'number', 
         'list' => array("New Technology", "Web-PHP", "Infrastructure", 
                         "Mobile Apps", "Mobile & More", "Vendor Showcase")),
   array('q' => "3", 'text' => "Pre Conference Communication", 
         'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "4", 'text' => "Conference Registration Process", 
         'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "5", 'text' => "Conference Check-in Process", 
         'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "6", 'text' => "Conference Tote bag and materials", 
         'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "7", 'text' => "Conference Facilities", 'reporton' => 'mc', 
         'qtype' => 'e'),
   array('q' => "8", 'text' => "Conference Location", 'reporton' => 'mc', 
         'qtype' => 'e'),
   array('q' => "9", 'text' => "Breakfast", 'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "10", 'text' => "Breaks", 'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "11", 'text' => "Lunch", 'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "12", 'text' => "Vendor Expo", 'reporton' => 'mc', 
         'qtype' => 'e'),
   array('q' => "13", 
         'text' => "Are you interested in a 2-day Rational Tools class", 
         'reporton' => 'mc', 'qtype' => 'yn'),
   array('q' => "14", 'text' => "How should handouts be distributed", 
         'reporton' => 'mc', 'qtype' => 'handouts'),
   array('q' => "15", 
         'text' => "How well did the conference meet your expectations?", 
         'reporton' => 'mc', 'qtype' => 'e1'),
   array('q' => "16", 'text' => "What was your overall Conference Experience", 
         'reporton' => 'mc', 'qtype' => 'e'),
   array('q' => "17", 
         'text' => "Will you be able to apply what you learned to your work?", 
         'reporton' => 'mc', 'qtype' => 'yn'),
   array('q' => "18", 'text' => "Will you want to come to future conferences?", 
         'reporton' => 'mc', 'qtype' => 'yn'),
   array('q' => "19", 'text' => "Question 19 is a dummy",
         'reporton' => 'none', 'qtype' => 'none'),
   array('q' => "20", 'text' => "Was your conference paid by:", 
         'reporton' => 'mc', 'qtype' => 'paidby'),
);

$sessconfig = array ("Teaching & Presentation Skills", 
                     "Session Content", 
                     "Class Management Skills", 
                     "Handouts", 
                     "Expectations Met");

?>
